### ISSUE TITLE
get-xkcd errors with Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by DunlapOverbelt** [poshbotio/PoshBot.XKCD#3]
## Current Behavior

Running PoshBot on Windows Server 2016 Standard with POSH version 5.1, an error like below is recorded whenever get-xkcd is run.
Invoke-RestMethod http://xkcd.com/info.0.json
Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-RestMethod http://xkcd.com/info.0.json
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

## Expected Behavior

A secure connection should be establish, however the there seems to be an incompatibility with the default security protocol used by powershell versus the server.

## Possible Solution

Putting the following at the top of PoshBot.XKCD.psm1 appears to fix the issue:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

## Steps to Reproduce (for bugs)

1. [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls
2. Invoke-RestMethod http://xkcd.com/info.0.json
3.
4.

## Context

With out the fix applied above, I could not enjoy the PoshBot.KCD plugin due to lack of comics loading.
This post was helpful in understanding the problem and fix:
http://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/
## Your Environment

* Module version used: PoshBot 0.7.1 PoshBot.XKCD 1.1.0
* Operating System and PowerShell version: Windows Server 2016 Standard with POSH version 5.1.14393.1066
.Net Framework 3.5 and 4.6 installed

**Comment by devblackops** [comment]
Good catch @DunlapOverbelt. Do you want to put in a PR for this and probably change the XKCD URLs to `https` since they redirect to that anyway?

**Comment by devblackops** [comment]
Fixed in 9277bfa165f83b8d936f40e67cb24efe1ea7dd4a.
